### ISSUE TITLE
Rename DerivedFeatures to avoid confusion with Derived Models

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#103]
As per our [Reference Architecture](https://github.com/LIonWeb-org/.github/blob/main/profile/README.md), we have a thing called *derived models*.

In our M3, we're about to finalize *derived features* (#6).

These two names are too similar, they provoke confusion.
So we should rename derived features.

Proposals:
* `ComputedFeature`
* `CalculatedFeature`

**Comment by enikao** [comment]
Can be closed as we decided to abandon Computed Features (#6)

**Comment by joswarmer** [comment]
Should close this
