### ISSUE TITLE
[documentation: Reference] Reference architecture

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/specification#123]
Currently in both the top-level README and in [this GDoc](https://docs.google.com/document/d/1_dsGs6RxcFEuTfnKmTDckllOLqzhsvwfKvmCZThBexs/edit#heading=h.j4l4qci8q98p).

**Comment by enikao** [comment]
See https://lionweb-io.github.io/specification/reference-architecture/reference-architecture.html

**Comment by joswarmer** [comment]
Should close this
