### ISSUE TITLE
[documentation: Reference] LIonCore/M3

### ISSUE THREAD

**Issue by dslmeinte** [LionWeb-io/specification#125]
* Goal and scope - currently [here](https://github.com/LIonWeb-org/organization/blob/main/lioncore/m3-goal-and-scope.adoc)
* Description including constraints - currently [here](https://github.com/LIonWeb-org/organization/blob/main/lioncore/metametamodel.adoc)

**Comment by enikao** [comment]
See https://lionweb-io.github.io/specification/metametamodel/metametamodel.html

**Comment by joswarmer** [comment]
Should close this
