### ISSUE TITLE
Sending a sub-tree to be attached to an existing parent

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/specification#132]
Imagine this case:
- On a client we know a node `a`
- We receive a subtree which contains a node `b`, which parent is `a`

At this stage we cannot support this case, because when we receive `b` we know we should attach it to `a`, but we do not know under which `containment` we should put it.

This is an example of the serialization of a node:

```
    {
      "id": "file_properties-parser-examples-example1-props--props2-value0",
      "concept": {
        "metamodel": "io_lionweb_Properties",
        "version": "1",
        "key": "io_lionweb_Properties-StringValue"
      },
      "properties": [
        {
          "property": {
            "metamodel": "io_lionweb_Properties",
            "version": "1",
            "key": "io_lionweb_Properties-StringValue-value"
          },
          "value": "foo"
        }
      ],
      "children": [],
      "references": [],
      "parent": "file_properties-parser-examples-example1-props--props2"
    }
```

if we added a key called `containing_link` with a metapointer of the containment link used in the parent to contain the node, then we could be able to plug received subtrees into an existing parent node which was built on the client side or received previously and not transmitted at the same time as the parent.

**Comment by enikao** [comment]
Relates to #167

**Comment by enikao** [comment]
I'd guess this is outdated?

**Comment by ftomassetti** [comment]
I think this is still the case: this is still a case we cannot support, both probably the only action we can take is to send an appropriate error message when this happens.

**Comment by joswarmer** [comment]
@ftomassetti You are right, this should result in an error message.
