### ISSUE TITLE
Have a default way to manage derived properties of nodes

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#16]
Examples:
* Type of the node
* Interpretation result

## Option A: Represented as `DerivedFeature`
Pro:
* No structural changes in M3

Con:
* Might need support of `DerivedProperty` and native custom types in M3, e.g. if interpretation result can be any Java `Object`.
* Calculation of derived property might involve lots of scoping, re-calculation based on events, etc.
  We don't want these aspects to creep into M3.

## Option B: Represent as separate aspect outside M3
Pro:
* Don't inflate M3
* Separation of concerns

Con:
* Harder to access

## Decision: Option B
Rationale: 
* too invasive for M3
* easier to postpone
* we don't understand the issue well enough yet

**Comment by enikao** [comment]
Is this about derived models, not only properties? Then we should add _derived_ tag.

**Comment by dslmeinte** [comment]
I think this particular should just fold into the bigger work for derived models, without a need for this small context. So, let's close it.

**Comment by enikao** [comment]
Will be discussed as part of #181.

**Comment by joswarmer** [comment]
Should close this
