### ISSUE TITLE
Annotation instances are stored under nodes

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/specification#164]
Currently we store the annotation instances with nodes: https://github.com/LIonWeb-org/organization/blob/main/serialization/annotation-variants.json

I think that we should either rename "nodes" into "classifierInstances" or alternatively have two top-level collections: "nodes" and "annotations"

**Comment by ftomassetti** [comment]
Related to this:
* the annotation instances specify their annotation under "concept". We could rename "concept" into "classifier" or specify "annotation"
* the annotation instances list their containments, but annotations cannot have containments

**Comment by enikao** [comment]
> Currently we store the annotation instances with nodes: https://github.com/LIonWeb-org/organization/blob/main/serialization/annotation-variants.json
> 
> I think that we should either rename "nodes" into "classifierInstances" or alternatively have two top-level collections: "nodes" and "annotations"

I like the current structure and names: `node` is lower level, so everything is a node.
What would be the advantage of two collections? If we really wanted to separate them (e.g. for performance reasons), that should be a parameter on the API.

**Comment by enikao** [comment]
> Related to this:
> 
>     * the annotation instances specify their annotation under "concept". We could rename "concept" into "classifier" or specify "annotation"

I don't like `annotation`, as this would again be on a too high level of abstraction -- we're talking about _nodes_, on that level there's no difference between concept or annotation.
`classifier` would be a bit more consistent, I agree.


> 
>     * the annotation instances list their containments, but annotations cannot have containments

Why not? `Annotation` is a `Classifier`, thus has `features`. This means, an `Annotation` can have any kind of `Feature`, incl. `Containment`. In turn, an instance of `Annotation` can contain whatever it wants (more precisely: whatever is declared as `Containment`).

**Comment by enikao** [comment]
> My main concern is not about how we serialize them, it is more about calling annotations nodes, as to me they are two separate things.

What about

```mermaid
classDiagram

class Node {
    <<abstract>>
}

Node <|-- AnnotationNode
Node <|-- ConceptNode
```

**Comment by ftomassetti** [comment]
Yes, I like that.

In my PR ConceptNode is Node, ClassifierInstance is Node and AnnotationNode is AnnotationInstance, but the idea is very similar and I realize the names I used are not great

**Comment by enikao** [comment]
On, 2023-09-29, we **decided to serialize both annotation instances and concept instances in the same list `nodes`.**

Rationale:
* Structurally, they are identical.
* We can refer to both of them in Links. If we had two lists, an implementation would need to search through both of them to resolve a link.
* We cannot differentiate between annotation instances and concept instances from the node only, but can do so as soon as we know the metamodel. That's the common case.

**Comment by joswarmer** [comment]
Should close this
