### ISSUE TITLE
Version scheme for LionWeb?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#165]
Which version scheme do we want to use?

Options:

1. SemVer `1.2.3`
2. Time-based (tags) —> `2023.1` (Year.incremented integer starting at 1)
   * Pro
      * Gives some indication about order and time
   * Con
      * Might feel outdated, even if “just” stable
3. City names `Aachen`
4. Single integer `1`

Related issues:

#130 decided that versions are only about _identity_ and _relation_, nothing more implied.

#58 decided that M3 and serialization format share a version, i.e. an M3 and the corresponding serialization format always have the same version.

**Comment by enikao** [comment]
**Decision on 2023-09-19 in [Slack](https://lionweb.slack.com/archives/C05737CGZDE/p1694810242834269): Time-based**

This also means we change the format of `serializationFormatVersion` field in serialization.

**Comment by joswarmer** [comment]
Should close this
