### ISSUE TITLE
Change spelling: LIonWeb -> LionWeb (lowercase i)

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#168]
LIonWeb (`LIonWeb`)  looks the same as LlonWeb (`LlonWeb`) in several often used font families. It’s a nuisance.
Also, some package managers have limitations on allowed capitalization.

We could change the name.

Proposals:

* `LIonWeb`
* `LionWeb`
* `Lionweb`
* `lionweb`
* `lion-web`
* `li-on-web` (looks like in NPM they replace capital letters with "-" as a separator)

*Decision on 2023-09-15 via [Slack vote](https://lionweb.slack.com/archives/C05737CGZDE/p1693836699551459): LionWeb*

We also adjust ids, repository names, etc. as far as possible -> #163.

**Comment by joswarmer** [comment]
Should close this
