### ISSUE TITLE
Create first release 2023.1

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#169]
In #165, we've decided for time-based version scheme, so the release name will be `2023.1`.
In #58, we've decided that serialization, M3, and builtins share the same version.

Version 2023.1 includes:

* Serialization format https://github.com/LIonWeb-org/organization/blob/main/serialization/serialization.adoc
* Meta-metamodel structure and semantics https://github.com/LIonWeb-org/organization/blob/main/metametamodel/metametamodel.adoc
* Builtins (same document as Meta-metamodel)

Validation logic for (meta)models included for TS.
NO thorough validation of different implementations against each other.

Version 2023.1 excludes:

* Any APIs

Other tasks to include:
* Resolve all TODOs from serialization / m3 docs
* Create GitHub tags / releases
* Maven releases of lionweb-java, lionweb-mps (also renames from lioncore?)
* NPM releases of lionweb-typescript, freon?
* Create Release notes
* Tag docs
* Keep change history

**Comment by enikao** [comment]
Added 2023-10-27:

Have some screencasts for the release
In dialog style

* @ftomassetti for LW-Java
* @dslmeinte for LW-TS

**Comment by joswarmer** [comment]
Should close this
