### ISSUE TITLE
Rename `concept` to `classifier` in node serialization

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#184]
As decided on 2023-09-29, we change the name of `concept` to `classifier` in node serialization.

Thus, nodes look like this:

```json
{
  "id": "aaa",
  "classifier": {
    "language": "myLanguage",
    "version": "2",
    "key": "myConceptId"
  },
  "properties": {},
  "children": {},
  "references": {},
  "annotations": [],
  "parent": null
}
```

Rationale:
* We want to keep the same serialization format for annotation instances and concept instances
* Pointing from an annotation instance to its defining annotation via `concept` is confusing
* In M3, the common supertype of `Annotation` and `Concept` is `Classifier`

**Comment by joswarmer** [comment]
Should close this
