### ISSUE TITLE
Are annotations part of "descendants" axis?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#185]
A common operation on (model) trees is to traverse the _descendants_ of a node (as defined in [XPath](https://www.w3.org/TR/1999/REC-xpath-19991116/#axes)). Do we consider annotations to be part of this axis?

Pro:
* annotations are part of the serialization node tree (#186). If we want to see _every_ node in the subtree, annotations should be included.

Con:
* As a language designer, I know which concepts I expect in a subtree of any given node. Another language might _extend_ my concepts, but they still need to adhere to my language structure. Annotations however can have any shape, and can be added by anybody. I can not hold any assumptions to them.
* In XPath, _descendants_ axis also does not include everything (attributes and namespaces are excluded).

Alternatives:
* A method `descendants(includeAnnotations: boolean)` with a parameter to select whether annotations should be included.
* Two methods `descendants()` to only include the descendants (without annotations) and `subtree()` that contains _both_ concept instances and annotation instances.

**Decision on 2023-09-29: "descendants" DO NOT contain annotations.**

**Comment by dslmeinte** [comment]
Sorry for chipping in after the fact:

- The intuitive semantic difference between `descendants()` and `subtree()` is small, so I think one `descendants(...)` function with options would be better.
- Configuring options using an object (or alternatively, a set of enum literals) is preferable to boolean-typed positional arguments.

**Comment by joswarmer** [comment]
Should close this
