### ISSUE TITLE
Name of `parent` field in serialization

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#187]
In #186, we decided that `parent` is the inverse of either `children` or `annotations`.

What would be a good name for that field?

# Alternative A: "parent"
Pro:
* Established for tree structures

Con:
* Might be confusing, as it's commonly understood as the inverse of "children"

# Alternative B: "container"
Pro:
* Generic enough to encompass inverse of both `children` or `annotations`

Con:
* Easy to confuse with M3 "Containment" (constant issue in EMF Ecore)

# Alternative C: "owner"
Pro:
* Generic enough to encompass inverse of both `children` or `annotations`

Con:
* Easy to confuse with lock owner as in #30, or organizational owner as in #27

**Decision on 2029-09-29: Alternative A: "parent".**

**Comment by joswarmer** [comment]
Should close this
