### ISSUE TITLE
Rename `ConceptInterface`?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#190]
The name `ConceptInterface` is a bit outdated, as it now also is a AnnotationInterface. Do we want to change this? Or are we ok to lave it this way? Maybe change it to `ClassifierInterface` (in line with #184)?

**Comment by dslmeinte** [comment]
Or even `Interface`?

**Comment by ftomassetti** [comment]
I would go for ConceptInterface, as in the implementation we may have interfaces that do not correspond to a ConceptInterface (e.g., `Serializable`)

**Comment by enikao** [comment]
**Decision via [Slack](https://lionweb.slack.com/archives/C05737CGZDE/p1697012126561249): `Interface`**

Rationale: 
* `ConceptInterface` does not fit anymore, as ``Annotation``s also implement Interfaces.
* `ClassifierInterface` would fit, but feels cumbersome.
* `Interface` does conflict with host language concepts (e.g. Java's `interface` keyword and concept), but so does almost every other name in our M3 (e.g. TypeScript standard library has a type `Node`).

**Comment by joswarmer** [comment]
Should close this
