### ISSUE TITLE
Change builtins language name?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#195]
(from [Jos' thread](https://lionweb.slack.com/archives/C05737CGZDE/p1696952889945859))

Is there a reason why we have as key LionCore-builtins and as id Lioncore.builtins for the builtins language (similar for LionCore-M3/.M3)? 
It's useful to have different `name` and `key` to not mix them up.

But I was hoping to get rid of the dot, as the language name can be part of a qualified name and often these are represented with dots between the names.
According to the metametamodel :
> A IKeyed’s `name` MUST be unique within the namespace (i.e. Language, Classifier, or Enumeration). The name MUST be a valid programming language identifier.

As Language is an IKeyed, I think that the `name` of a language should be a valid identifier and not contain a dot.

**Comment by enikao** [comment]
**Decision on 2023-10-12: Rename builtin languages to `Core_M3`, `LionCore_builtins`.**

Rationale:
* Keep `name`, `key`, and `id` different so they're not mixed up
* Adhere to #48

**Comment by dslmeinte** [comment]
`LionCore_M3` or really `Core_M3`?

**Comment by joswarmer** [comment]
Should close this
