### ISSUE TITLE
In Serialization, specify that a targets array in a reference can be empty

### ISSUE THREAD

**Issue by AtanasM98** [LionWeb-io/specification#200]
We can have a reference that doesn't have any targets, but it was hard to understand that when reading the [reference spec](https://lionweb-io.github.io/specification/serialization/serialization.html#reference).

**Comment by enikao** [comment]
Is this sufficient? https://github.com/LionWeb-io/specification/pull/199/files#diff-2808a6aca59bffdeed73a4f12c003bc477c5a1cf034024a5bd05ecdef3479d01R123-R132
