### ISSUE TITLE
rename `nodes.children` -> `nodes.containments`?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#206]
We currently use the term `children` in two places in serialization: `nodes.children` and `nodes.children.children`. That's confusing.
Shall we rename the first level to `containments`, i.e. `nodes.containments.children`? That's also in line with the M3 names.

**Comment by enikao** [comment]
**Decision on 2023-10-27: Rename to `nodes.containments.children`.**

**Comment by joswarmer** [comment]
Should close this
