### ISSUE TITLE
We always transmit complete nodes in bulk API

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#211]
If we transmit a node in bulk API, that node must be _complete_.

_Complete_ means the node MUST contain
* its id
* its classifier meta-pointer
* all its property values
* all its containments with all contained node ids
* all its references with all target node ids
* all its annotation node ids
* its parent node id

**Comment by joswarmer** [comment]
See https://github.com/LionWeb-io/lionweb-repository/issues/20 for special uses case of this issue.

**Comment by enikao** [comment]
Fixed the part about parent
