### ISSUE TITLE
Can we send features during createPartition()?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#225]
In #216, we decided for an explicit `createPartitions` operation.

Can the nodes sent as new partitions contain features?

## Properties
Pro:
* Useful to work with the new partition, e.g. immediately assign a `name`.

## Annotations/children
We cannot send the target nodes in the same request, as all sent nodes become partitions.
According to #223, annotations/children MUST be known to the repository.
Thus, we could only _move_ other nodes to become descendants of the new partition.

Con:
* Complex move logic as part of this operation.

## References
Pro:
* No technical issues, as references might point to unknown nodes

Con:
* Might feel asymmetric to descendants

**Comment by joswarmer** [comment]
Good point. I think that you would almost always want to give a new partition a name.

**Comment by enikao** [comment]
* Next call after + `createPartition()` is probably a `store()` to fill the partition, which could also fill the properties
* As we cannot send children, we must allow nodes that violate _required_ attribute of feature
* What happens if we `store()` a node with is not contained anywhere?
  * Immediately becomes an orphan
  * Or error message?
* Can we translate an existing non-partition node into a partition?
  * Implies we need to change the concept of that node, because partition concepts cannot be nested
  * Acceptable limitation: Would need to create a new partition, move contents there, redirect all references, delete existing non-partition
* Can we move a partition to become a child?
  * Feels symmetric not to allow it
  * Might be hard for the backend, if it relates a partition to specific storage (e.g. a file, an MPS model)

## Decision: Allow properties and references, disallow annotations and containments
