### ISSUE TITLE
Does bulk API validate against languages?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#226]
In a bulk API request, does the repository check the request for consistency w.r.t. the language?

This relates to:

* classifier of node exists
* if node is an annotation: node's classifier can annotate parent's classifier
* if node's classifier is not an annotation: node can exist as child in its parent's classifier
* if node is used as a partition: node's classifier is marked as partition
* if node is not used as a partition: node's classifier is not marked as partition
* nodes mentioned in `annotations` are annotations
* metapointers of properties are part of the node's classifier
* property values adhere to its classifier type
* all required properties are set
* metapointers of containments are part of the node's classifier
* nodes mentioned in `containments` are not annotations
* nodes mentioned in `containments` fit the metapointer of the containment
* all containments adhere to their cardinality (required ones are present, only multiple ones have more than one child)
* metapointers of references are part of the node's classifier
* nodes mentioned in `references` fit the metapointer of the reference
* all references adhere to their cardinality

Pro:
* All participants can assume valid models (after initial validation)

Con:
* The repository has to check the validity on every request. This might be expensive (we have to care for all concept inheritance and polymorphism)
* We can never change a language without changing its version (useful during development)
* If there is an issue with the model, we need a "backdoor" to the repository to fix it
* For required children (including transitive) and references, we can only store the model once we've created the whole required subtree
* Parser-based clients can only store valid ASTs, or have to use extremely leniently designed languages. Especially for interactive editors, the AST is invalid most of the time.

**Comment by enikao** [comment]
What happens with repositories that _do_ support invalid models (e.g. MPS)? Do they just omit the invalid parts? They would get lost as soon as the model is stored back.

**Comment by dslmeinte** [comment]
I think a repo that's aware of the languages involved could _optionally_ do validation w.r.t. those languages (if prompted to do so), but must not have other behavior attached to that. That would make clients needlessly complicated and prohibit language evolution.

**Comment by joswarmer** [comment]
Just for clarification, we have three options:

**Option A: Bulk API never checks against languages**
Simple solution, but depends heavily on every client being 100% correct

**Option B: Bulk API always checks against languages**
More complex repository logic, but always a guaranteed correct model, no dependencies on all client being 100% correct.

**Option C**: Bulk API optionally checks against languages
This should be a setting defined by the repository because it is of little added value if only some of the requests are check as the repository might have incorrect models anyway and client need to take the same precautions as in option A

I am in favour of option B, for the following reasons
- looking from the client perspective, each chunk I get has the guarantee that it conforms to the language(s). Otherwise there are barely any guarantees and clients need to be able to handle random collections of nodes.
- as Niko already mentioned, if we allow incorrect chunks, we need to specify exactly what the repository will do for each incorrectness. That will make the specification overly complex.

**Comment by joswarmer** [comment]
Feedback on the Cons mentioned:

- The repository has to check the validity on every request. This might be expensive (we have to care for all concept inheritance and polymorphism)
    - Could be expensive, but by pre-processing the language(s), this can be optimised a lot
- We can never change a language without changing its version (useful during development)
    - Never change language without changing its version  is something that we already require and what we definitely want
    - In a development environment you should always be able to use backdoors, but I think that we are not defining a development environment (and we shouldn't).
    - It is perfectly ok to have a 'development' mode for a repository where you are able to do things normally not allowed.
- If there is an issue with the model, we need a "backdoor" to the repository to fix it
    - Indeed, but I do not think that backdoor is something that we should define in the specification.
- For required children (including transitive) and references, we can only store the model once we've created the whole required subtree
    - This raises the question to what extent we check against the language, I can imagine that required children not need to be checked. 
- Parser-based clients can only store valid ASTs, or have to use extremely leniently designed languages. Especially for interactive editors, the AST is invalid most of the time.
    - Parser based clients will store the text of the model anyway (because that is the actual source), so nothing is lost.  And it probably is not very useful to store incorrect (and usually meaningless) information in a model-repository.

**Comment by enikao** [comment]
If we find a good way to deal with delivering invalid models to validating clients, I'd prefer option C.
Otherwise, I think we disable many use cases if we enforce validation, so I'd go for option A.

**Comment by enikao** [comment]
MPS, EMF, and Modelix all allow models that violate their language. Parsers go to great lengths to create partially invalid ASTs (_error recovery_).
I think we would be incompatible with most existing systems if we enforced valid models.

**Comment by enikao** [comment]
Regarding the "backdoor" to a repository, I see the difference between using low-level MPS API to fix a model, or editing the .mps file with a text editor (similar for EMF and .xmi files).
If we can only fix the model by editing the file, there's really no other way than going through the backdoor. But that's rarely needed. In most cases, the low-level API suffices.

**Comment by joswarmer** [comment]
As we think allowing erroneous models might be important, I think we should come up with use cases and see which ones we can or cannot support.

**Comment by dslmeinte** [comment]
I strongly feel that the API shouldn't make much difference between valid and invalid models – insofar we even have a clear definition of that! The client shouldn't need to use a “backdoor”/low-level API to fix things, especially not if issues come to light during regular operation of the API.

(Just stating this is a guiding principle of sorts, not to say anyone is proposing to go the other direction.)

**Comment by joswarmer** [comment]
I can imagine that we allow certain kinds of invalid models, like e.g. partial models where e.g. a mandatory child is missing. It is hard to imagine invalid models in general, as clients then need to be able to handle random trees with random content. It seems that this effectively requires every client to be fully generic. Aren't we missing the point of having metamodels if we allow this?

Alternative guiding principle: we allow partial models, where the part of the AST that is there conforms to the metamodel. More explicitly I am thinking of something like:
- allow missing mandatory children, missing property  values, etc.
- If we find a good way to attach incorrect "user input" (not an AST, but probably just text) we can support that using e.g. annotations
- we do not allow the use on MetaPointers that do not resolve to a node in the used language definitions.
- we only allow features of a node (properties, containments, references) if they are defined as feature of its classifier.

**Comment by joswarmer** [comment]
**Use Case 1: Incorrect parsed text**
The user edits a text, which is parsed with one or more errors. He wants to store this in a LionWeb repository

- Scenario 1: the user saves the file as text and the next time he wants to edit, he opens the text file. 
  In this scenario there is no direct need to store invalid text in the repository as the original text is always used. We might or might not allow the part of the text that parses into a partial AST to be stored.
- Scenario 2: the user stores everything in the repository and when he wants to edit it he retrieves the AST from the repository, which is then unparsed into text that the user can edit. 
  In this scenario it is useful to store any incorrect text in the repository, otherwise it will be lost. We can store the partial AST, and attach the incorrect text to it. The main requirement is that we can put this text at the original position in the unparsed AST.

**Comment by enikao** [comment]
**Use case 2: Editor with hard-coded domain classes**

An editor (graphical / form-based / projectional) uses generated classes (derived from LW language) to represent the model. It has no way to handle nodes of unknown classifiers, or unknown features, as they don't appear in the generated classes.

**Comment by enikao** [comment]
**Use case 3: Generator**

A generator in some technology (e.g. MPS, Xtend) assumes valid input models, as it doesn't want to deal with all possible cases a model might be wrong.

**Comment by enikao** [comment]
**Use case 4: Language workbench for rapid prototyping**

The language engineer uses a LWB to explore&build a domain model. The repository (e.g. MPS, EMF-based) supports changing existing languages. As the languages change all the time, the language engineer doesn't want to bother with tracking language versions.
The language engineer wants to adjust instance models to changes in the language without using a "backdoor" (i.e. changing the underlying repository storage).

**Comment by enikao** [comment]
**Use case 5: Fixing bug in model**

Due to an implementation bug in a language, a client, or the repository, the model becomes invalid. An expert user (e.g. language engineer) uses a low-level API to fix the model.

**Comment by enikao** [comment]
**Use case 6: Deeply nested required containments**

In a GPL-like language, a package must have at least one class, which must have at least one method, which must have a body, which must have at least one statement.

The user creates a package and class. Then, the user wants to write down all envisioned methods before implementing them.
The user wants to store the model even with some implementations missing.

**Comment by enikao** [comment]
**Use case 7: Model migration**

A model is an instance of Language `A@x` (version x). `A@x` contains 10 concepts. Now Language `A@y` is released, which changes 3 of the concepts. A processor wants to migrate all instances to `A@y`.

**Comment by enikao** [comment]
**Use case 8: Language-specific validator**

A processor wants to check a model. The processor checks both the structural validity of the language (cardinalities, type conformance, etc.), as well as language-specific checking rules it somehow knows about.

If this processor doesn't find any errors, the user can be confident the model is valid w.r.t. the domain.

**Comment by enikao** [comment]
**Use case 9: Completely generic editor**

**Comment by enikao** [comment]
Additional thoughts from discussion:

Separation of concerns: Repo stores models, validation is another processor
We store models adhering to languages, not arbitrary data
We store models adhering to M3
How to transport model validity information?

**Comment by enikao** [comment]
To me, it seems _vital_ to support model content that violates its language definition:

* Without that, we would define a protocol that's incompatible with all existing reference systems (MPS, EMF, Modelix), as all of them support such model content.

* I don't see the issue for clients dealing with such models -- both our Java and C# implementation handles them automatically.

* It is possible to build a validating API on top of a non-validating API, but not vice versa.

**Comment by ftomassetti** [comment]
I agree with @enikao that is vital to support model content that violates its language definition.

At the risk of repeating something we stated multiple times, I think that this discussion, as many others, would benefit from discussions on use-cases and even better from building POCs. I think that in that sense the model repository is a game changer, as we can experiment more and refer to concrete situations encountered in our discussions

**Comment by joswarmer** [comment]
Seems we are starting to have a majority that is in favor of allowing incorrect models, so we should think about how invalid they may be and how we deal with this in the API.

**Comment by joswarmer** [comment]
> * It is possible to build a validating API on top of a non-validating API, but not vice versa.

Indeed.

**Comment by joswarmer** [comment]
> * Without that, we would define a protocol that's incompatible with all existing reference systems (MPS, EMF, Modelix), as all of them support such model content.

I do not recall EMF allowing incorrect models, so it would be useful to find out how incorrect models are supported in all the referred systems.

**Comment by enikao** [comment]
> I do not recall EMF allowing incorrect models, so it would be useful to find out how incorrect models are supported in all the referred systems.

I mainly remember debugging through EMF built-in validators. They check for all the M2 constraints, so I guess they can be violated.
