### ISSUE TITLE
When moving a node, do we need to mention both source and target parent?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#227]
Assume the repository contains node with id `x` and `y`. `x` _contains_ `y` as child.

We send a store request to move `y` from its previous parent `x` to its new parent `z`.
We don't change `y` in any other way.

Which nodes do we need to send in the request?

## Option A: Mention both previous (`x`) and new parent (`z`)
Pro:
* No implicit changes

Con:
Client needs to know the previous parent. How to announce this in bulk API to client?
If the repo does not announce it, the client has to loop over every node used as child/annotation (because the client does not know which move failed), retrieve its parent, and send the parent along.

## Option B: Send only old parent (`x`)
Makes no sense -- how would we know `y` is moved?

## Option C: Send only new parent (`z`)
Pro:
Fits with bulk idea: Client sends how the world should be

Con:
* Implicit changes to previous parent (`x`)

## Option D: Send only child (`y`) and mention its new parent
Does not work: if `z` contains `y` in a multi-value containment (or as annotation), at which position do we enter `y`?

# Decision: Option C: Send only new parent

**Comment by joswarmer** [comment]
For moving _y_ we need to know to which containment(including at which position) in the new parent the node _y_ is moved. This cannot be done by sending the moved node.

The way to move the node is to send the new parent _z_ with node _y_ in one of its containments. There is no need to send _y_ at all, as the repository will make sure it is removed from its previous containment in parent _x_.  
However if _y_ is sent in the same request, it must have _z_ as its parent.

Note that a node can also be moved from one containment to another containment in the same parent.
