### ISSUE TITLE
Must M2 nodes have unique node ids, even for two versions of the same language?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#240]
Assume a language `issues` in version 1:

```
language [id=5]
  name="issues"
  key="iss"
  version="1"
  entities:
    concept [id=50]
      name="warning"
      key="w"
```

Then we release version 2 with some changes:

```
language [id=6]
  name="issues"
  key="iss"
  version="2"
  entities:
    concept [id=60]
      name="warn"
      key="w"
```

In the example, issues@v1 has id 5, different from issues@v2 (id 6).
Is this required?

If both languages are never part of the same repository, we could just change `[5].id` from `1` to `2` and `[50].name` from `warning` to `warn`.

TODO: What happens then?

If both languages exist in the same repository at the same time, they MUST have different node ids, as node ids MUST be unique in the repository:
A new language version MUST be its own node (because it changes its `version` property),
Then, all contained nodes MUST be copied (because they are children of a different node, and we cannot share children between nodes).

We don't want to make exceptions for languages w.r.t. their node nature.

This implies comparing two language versions MUST use a diff tool that ignores node ids.

Relates to #239

**Comment by joswarmer** [comment]
Although technically nodes with different id's are not the same, I understand the point.  This means the language diff should use the _version_ + _key_ as the identity of a node.
