### ISSUE TITLE
Repo API: Bulk read/write

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#25]
Ask the model repository for some subset of the stored model, and update it.

## Assumptions for time being
* No federation/references to external repositories (#23)
* No versioning (#26)
* No access control (#27)
* No partitioning (#29)

## Assumptions
* Reference nodes by id (#31)

## Conceptual API
Independent of implementation (will most probably be REST, but could also use Protobuf etc.)

### retrieve part of model
in: (list of) node IDs
in: mode {node, subtree, closure}
out: (list of) subgraph(s)

### store part of model
in: (list of) subgraph(s)
out: success

### Give me a range of IDs I can use 
TODO:
in: Number of ids required
out: list of reserved ids

**Comment by joswarmer** [comment]
> How do we report back unknown ids? Example: I sent a list of 5 ids to the server in mode `node` (i.e. only asking for each node, neither subtree nor closure). 3 of the ids can be resolved, 2 not. How is this reported back to me?
> 
> (Relates to [discussion about resolve info](https://github.com/LIonWeb-org/organization/issues/36#issuecomment-1384070433))

Asking for nodes that do not exist in the repository is not an error, but a normal thing. Consider the following use cases:
- The model at the client contains an unresolved reference
- The client thinks a node exists, but in the mean time another client has changed the repository such that the node does not exist anymore.

Therefore, I think we should not explicitly report back unknown nodes.  The client can simply check whether a requested node is in the returned chunk or not.

**Comment by enikao** [comment]
Spec in #167
