### ISSUE TITLE
Can we have multiple instances of the same Annotation associated to a certain Node?

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/specification#32]
Let's suppose that I have an `Annotation` called `DocumentationComment`. Can I have multiple instances of this Annotation associated to the same Node? Is this true for all the Annotation or should this be something we define for each Annotation?

**Comment by enikao** [comment]
I think we decided on this in #13: An `Annotation` has a `multiple` flag, so we might have multiple instances of the same Annotation on the same Node.

**Comment by dslmeinte** [comment]
I'm reluctant to say anything more about this, but: Is it even necessary to have a `multiple` flag? It seems like it's not our business to restrict this: if it makes sense for someone to restrict an `Annotation` to be used (at most/exactly) once, then that'd be a constraint.

**Comment by enikao** [comment]
In the end it is only a constraint -- we can still have an (invalid) model that has two instances of the same annotation (with `multiple = false`) on one node.

I don't recall the discussion around this exactly. One argument was the influence on APIs (`getDocu(): Docu` vs. `getDocu(): sequence<Docu>`).

Shall we raise this again next week?

**Comment by dslmeinte** [comment]
When to call a model "valid" is also still very much up for debate, so we might want to tackle that one first ;)

**Comment by enikao** [comment]
We've **decided** some time ago _not_ to have `Annotation.multiple` flag.
