### ISSUE TITLE
Shouldn't Field also implement INamed?

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/specification#324]
I was expecting this to be the case but [here](https://lionweb.io/specification/metametamodel/metametamodel.html) and [here](https://raw.githubusercontent.com/LionWeb-io/specification/61e3f929afb57c94143c20906f94a682777fe0c8/metametamodel/lioncore.json) Field does not implement INamed

**Comment by enikao** [comment]
I think it does: `Field` implements `IKeyed`, which in turn extends `INamed`.

**Comment by ftomassetti** [comment]
Oh, right, I keep forgetting that IKeyed extends INamed
