### ISSUE TITLE
How to represent ComputedFeature in M3?

### ISSUE THREAD

**Issue by enikao** [LionWeb-io/specification#6]
For `DerivedFeature`, it makes no sense to distinguish between `Reference` and `Containment`.
Also, do we allow `DerivedFeature`s of `DataType`s?

## Option A: `DerivedFeature` next to other `Feature`s
```mermaid
classDiagram
Feature <|-- Property
<<abstract>> Feature
Property --> DataType: type
<<abstract>> DataType
Feature <|-- Link
<<abstract>> Link
Link <|-- Reference
Link <|-- Containment
Link --> AbstractConcept: type
<<abstract>> AbstractConcept
Feature <|-- DerivedFeature
DerivedFeature --> AbstractConcept: type
```

## Option B: `DerivedLink` next to other `Link`s
```mermaid
classDiagram
Feature <|-- Property
<<abstract>> Feature
Property --> DataType: type
<<abstract>> DataType
Feature <|-- Link
<<abstract>> Link
Link <|-- Reference
Link <|-- Containment
Link --> AbstractConcept: type
<<abstract>> AbstractConcept
Link <|-- DerivedLink
```

## Option C: `DerivedFeature` next to other `ConcreteFeature`s
```mermaid
classDiagram
Feature <|-- ConcreteFeature
<<abstract>> Feature
<<abstract>> ConcreteFeature
ConcreteFeature <|-- Property
Property --> DataType: type
<<abstract>> DataType
ConcreteFeature <|-- Link
<<abstract>> Link
Link <|-- Reference
Link <|-- Containment
Link --> AbstractConcept: type
<<abstract>> AbstractConcept
Feature <|-- DerivedFeature
DerivedFeature --> AbstractConcept: type
```

## Option D: Support `DerivedFeature` of `DataType`
```mermaid
classDiagram
Feature <|-- AbstractProperty
<<abstract>> Feature
<<abstract>> AbstractProperty
AbstractProperty --> DataType: type
<<abstract>> DataType
AbstractProperty <|-- Property
AbstractProperty <|-- DerivedProperty
DerivedFeature <|-- DerivedProperty
<<interface>> DerivedFeature
Feature <|-- Link
<<abstract>> Link
Link <|-- Reference
Link <|-- Containment
Link --> AbstractConcept: type
<<abstract>> AbstractConcept
Link <|-- DerivedLink
DerivedFeature <|-- DerivedLink
```

## Option E: Support `DerivedFeature` of `FeatureType`
```mermaid
classDiagram
Feature <|-- ConcreteFeature
<<abstract>> Feature
<<abstract>> ConcreteFeature
Feature --> FeatureType: type
<<interface>> FeatureType
ConcreteFeature <|-- Property
Property --> DataType: specializes type
<<abstract>> DataType
FeatureType <|-- DataType
ConcreteFeature <|-- Link
<<abstract>> Link
Link <|-- Reference
Link <|-- Containment
Link --> AbstractConcept: specializes type
<<abstract>> AbstractConcept
FeatureType <|-- AbstractConcept
Feature <|-- DerivedFeature
```

## Option F: Flag `Feature.derived`
```mermaid
classDiagram
class Feature {
  boolean computed
}
<<abstract>> Feature
```

**Comment by joswarmer** [comment]
No derived features at all in the metamodel, because we focus on Data Interchange level.  Derived features is a language API level concept.

**Comment by dslmeinte** [comment]
I agree with Jos: computed features should not go in the M3 at all. I very much prefer to Separate Concerns here. The M3's concern is Data Interchange. Computed features are about using models once they're exchanged (code generation, etc.), which is an entirely different thing.

Why not define another M3 specifically for expressing computed features with. Any M2 can be augmented by an CF-M2 conforming to the CF-M3 (CF = Computed Feature). This also gives a lot more flexibility. Also: constraints (and probably the underlying type system) can go in the same mould.

**Comment by ftomassetti** [comment]
While I originally thought that Computed features were useful to have here, I now also think that should not be part of M3, and stay somewhere else (as suggested by @dslmeinte)

**Comment by enikao** [comment]
**In the meeting on 2023-09-15, we decided to _not_ have `ComputedFeature` in core M3.**

**Comment by joswarmer** [comment]
Should close this
