### ISSUE TITLE
Node update: do we allow concept change?

### ISSUE THREAD

**Issue by markusvoelter** [LionWeb-io/specification#69]
When we update a node -- for example as part of the bulk API -- do we want to allow a change of the concept?

This way, we can keep references alive even though something changes, say, from a global constant to a function call. Obviously, the updated node must contain all the children and properties defined by the new concept.

Alternatively, the server should refuse the update if the concept is changed.

**Comment by enikao** [comment]
If model migration is executed by a (regular) processor, we _must_ allow concept change -- the migrator would at least change the concept from `{langX, v1, conceptY}` to `{langX, v2, conceptY}`. According to #213, that's a concept change.

**Comment by joswarmer** [comment]
Sounds like we need this, the current lionweb-repository does not allow this, or better said, it ignores the classifier once a node has been stored for the first time.

**Comment by enikao** [comment]
## Decision: Repository MUST support meta-pointer change.

This means that an update command can send an already existing node id with a different `classifier` than the existing node.

(Decided on 2024-03-01)

Rationale:
* It is required for migration scenarios.
* Only supporting it optionally complicates the specification and testing.
* The scenarios where changing the classifier might be hard seem far-fetched. We might re-visit this decision if experience shows more common scenarios.
