### ISSUE TITLE
Can Repositories have stricter requirements on node IDs than LIonWeb (e.g. only longs)?

### ISSUE THREAD

**Issue by markusvoelter** [LionWeb-io/specification#70]
As part of Lionweb, we have not said anything about how node IDs are structured, beyond the Base64 decision. However, specific repositories might make assumptions about this ID. For example, modelix assumes longs. This means:
* if we receive data from the server that has nodes  in it, their IDs are assumed by the client to be valid for the repo
* if the client creates new nodes, they have to use IDs that are valid for the repo. Best way of doing is is for the client to request a pool of new IDs from the server for each editing session (we need an API for that)

One consequence of this approach is that nodes and their IDs might not be portable across repos. However, when we import a bunch of nodes into a different repo, we will likely have to touch the IDs anyway because they might overlap with existing ones. So the additional burden of changing the format (arbitrary string to, say, long) is not a huge additional burden.

**Comment by enikao** [comment]
Considerations:
* Importing models always needs id mapping: if the repo already contains a (semantically different) node with the imported id, the repo _must_ map the imported id
* What are performance / complexity implications for implementers?
  * Repo might need two internal lookup indices: One for internal ids, one for LIonWeb ids.
* If we establish limited supported ids (aka stricter requirements), it always influences the API:
   * We either need a repository API like `getNewId()`, to retrieve valid ids from the repo.
   * Or a client can send arbitrary ids, and the repo communicates back if the ids were mapped in some way. Then the protocol needs to support this communication.
* There is always one party that has to do the extra work: Either the client has to take care of using only valid ids, or the repo has to map external LIonWeb ids to its internal representation.
* Repository is a persistent storage: Should be easier to store mapping between ids
* Probable (most important?) first use case: Compatible systems communicate → id-compatible “by default” (e.g. Modelix with Modelix or MPS with MPS)

**Comment by enikao** [comment]
**Decision for now for the sake of progress: Every LIonWeb participant has to accept every valid id**

Rationale: We don't have enough experience. This is the easiest way forward for now, and doesn't limit future options too much.

→ No mapping on protocol level required
