### ISSUE TITLE
Do we need to represent BaseConcept?

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/specification#71]
When specifying the type of a reference or a containment we currently have no way to indicate that any node is acceptable. To be able to do that I think we would need the Equivalent of BaseConcept : a Concept representing the common ancestor or every Concept. Or is there a different way to represent this?
Should BaseConcept added to the LionCore metamodel? Or should it be added to the builtins metamodel?

**Comment by enikao** [comment]
For reference: The agreed ids and keys are listed in [metamodel docs](https://lionweb-org.github.io/organization/lioncore/metametamodel/metametamodel.html#_pre_defined_ids_and_keys)
