### ISSUE TITLE
Bulk API atomicity

### ISSUE THREAD

**Issue by joswarmer** [LionWeb-io/specification#75]
Use case: 

- we have a node A with child C.
- the client moves node C to a new parent B.
- the client wants to use the bulk API to send this change to the server

How does the client have to do this? I see at least two options:

1. send node B with child C.
   If the server accepts this, then the server needs to remove C as child from A, meaning that the server changes A.

2. send node B with C and node A.
   The server can apply all changed nodes, no server initiated changes are needed.

The question this raises is how to send a bulk API call with changed nodes:

- do we allow the server to update nodes outside the ones it received and actively make changes to them (option 1), or
- de we require the API call contains a collection of nodes that, when applied, results in a consistent state (option 2).

Pro 1: 
- easier for the client, as it can send whatever it wants, the server will try to make things consistent

Con 1
- hidden side effects can make it very unclear what is actually changing in the server
- consistency between server model an client model is harder to maintain.
- more complexity in the server to make the model consistent
- Might send the change to B in a next API call, which is then redundant.

Pro 2:
- server is easier as it does not need to have functionality for making models consistent
- no implicit changes in the model, making it more predictable.

Con 2:
- the client needs to ensure it send s(a collection of) nodes that result in a consistent model.

**Comment by enikao** [comment]
relates to #127
